### ISSUE TITLE
bug: chich femboy tien

### ISSUE THREAD

**Issue by alicezuberg930** [tiesen243/yuki#1]
### Provide environment information

`chao femboy cua t`

### Describe the bug

decfvrndcf

### Link to reproduction

http://127.0.0.1:8000/user/profile

### To reproduce

fwtgrfed

### Additional information

`chich tien suot ngay`

**Comment by tiesen243** [comment]
![anime-fandoms-yukikaze-(azur-lane)-4474481.jpeg](https://github.com/user-attachments/assets/57998112-eadb-49bc-98cb-11877c685dbb)

xam l qua

**Comment by alicezuberg930** [comment]
Chung ta deu nhu nhau thoi dong chi

Vào 13:10 Th 3, 12 thg 11, 2024 Trần Tiến ***@***.***> đã
viết:
